# Generated by Django 4.1.5 on 2023-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(default='-', verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(default='profile/default-profile.png', upload_to='profile', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jop',
            field=models.CharField(default='-', max_length=50, verbose_name='İş'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(default='-', max_length=50, verbose_name='Telefon'),
        ),
    ]
