# Generated by Django 4.1.5 on 2023-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_product_discount_per_product_oldprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_per',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='İndirim Yüzdesi'),
        ),
    ]
