# Generated by Django 4.1.5 on 2023-06-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_total',
            field=models.FloatField(null=True, verbose_name='Ürün Puanı'),
        ),
    ]
