# Generated by Django 4.1.5 on 2023-06-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_product_rating_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_total',
            field=models.FloatField(default=0, verbose_name='Ürün Puanı'),
        ),
    ]
