# Generated by Django 4.1.5 on 2023-06-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_alter_product_rating_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Yoirum Puanı'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.userinfo', verbose_name='Kullanıcı'),
        ),
    ]
